# Email Server IMAP and SMTP configuration
# SMTP server should support Alias creation and deletion
# IMAP server should support IDLE

email-server:
  hosts:
    - trashemail.in
    - thromail.com
    - humblemail.com
  admin-email: contact@trashemail.in
  admin-password: changeme
  add-url: https://trashemail.in/admin/mail/aliases/add
  remove-url: https://trashemail.in/admin/mail/aliases/remove
  imap:
    host: trashemail.in
    port: 993
    email: contact@trashemail.in
    password: changeme

# Telegram bot specific settings
telegram:
  url: https://api.telegram.org/bot
  botToken: xxxxxxxxxxxxxxxxxxxxxx
  size: 4096

# For development purpose, H2 is used.
# I prefer H2 persistent in file.
spring:
  datasource:
    url: jdbc:h2:file:./AppDB;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
      enabled: true
  application:
    name: Trashemail

# Tomcat server settings
server:
  port: 9090

# Trashemail app server settings
trashemail:
  max-emails-per-user: 4

# Logger settings
logging:
  level:
    io:
      github:
        trashemail: debug
